from __future__ import annotations

from enum import StrEnum


class AuditEvent(StrEnum):
    LOGIN = "LOGIN"
    LOGOUT = "LOGOUT"
    REGISTER_USER = "REGISTER_USER"
    REGISTER_STUDENT = "REGISTER_STUDENT"
    REGISTER_GROUP = "REGISTER_GROUP"
    TEACHER_SCREENING_COMPLETED = "TEACHER_SCREENING_COMPLETED"
    RESPONSE_SUBMITTED = "RESPONSE_SUBMITTED"
    DIAGNOSIS_CREATED = "DIAGNOSIS_CREATED"
    REPORT_REQUESTED = "REPORT_REQUESTED"
    REPORT_GENERATED = "REPORT_GENERATED"
    ALERT_GENERATED = "ALERT_GENERATED"
    USER_DEACTIVATED = "USER_DEACTIVATED"
    MODEL_VERSION_ACTIVATED = "MODEL_VERSION_ACTIVATED"
    WIPE_TRIGGERED = "WIPE_TRIGGERED"
    SECURITY_EVENT = "SECURITY_EVENT"
