from __future__ import annotations

from enum import StrEnum


class AuditEvent(StrEnum):
    LOGIN = "LOGIN"
    LOGOUT = "LOGOUT"
    REGISTER_USER = "REGISTER_USER"
    REGISTER_STUDENT = "REGISTER_STUDENT"
    DELETE_STUDENT = "DELETE_STUDENT"
    PERMANENT_DELETE_STUDENT = "PERMANENT_DELETE_STUDENT"
    ACTIVATE_STUDENT = "ACTIVATE_STUDENT"
    REGISTER_GROUP = "REGISTER_GROUP"
    DELETE_GROUP = "DELETE_GROUP"
    TEACHER_SCREENING_COMPLETED = "TEACHER_SCREENING_COMPLETED"
    RESPONSE_SUBMITTED = "RESPONSE_SUBMITTED"
    DIAGNOSIS_CREATED = "DIAGNOSIS_CREATED"
    DIAGNOSIS_LABELED = "DIAGNOSIS_LABELED"
    REPORT_REQUESTED = "REPORT_REQUESTED"
    REPORT_GENERATED = "REPORT_GENERATED"
    ALERT_GENERATED = "ALERT_GENERATED"
    USER_DEACTIVATED = "USER_DEACTIVATED"
    MODEL_VERSION_ACTIVATED = "MODEL_VERSION_ACTIVATED"
    WIPE_TRIGGERED = "WIPE_TRIGGERED"
    SECURITY_EVENT = "SECURITY_EVENT"
    INSTITUTION_REGISTERED = "INSTITUTION_REGISTERED"
    INSTITUTION_APPROVED = "INSTITUTION_APPROVED"
    INSTITUTION_REJECTED = "INSTITUTION_REJECTED"
    PAYMENT_CHECKOUT_CARD = "PAYMENT_CHECKOUT_CARD"
    PAYMENT_CHECKOUT_CASH = "PAYMENT_CHECKOUT_CASH"
