from __future__ import annotations

from typing import Protocol


class RecommendationPort(Protocol):
    """Puerto hacia el Recommendation Service (rutas adaptativas, puerto 8002)."""

    async def recommend(self, payload: dict) -> dict: ...
    async def next_exercise(self, payload: dict) -> dict: ...
    async def get_exercise(self, exercise_id: str) -> dict: ...
    async def health(self) -> dict: ...
