from __future__ import annotations

from enum import StrEnum


class TestType(StrEnum):
    TEACHER_SCREENING = "TEACHER_SCREENING"
    PHONOLOGICAL = "PHONOLOGICAL"
    LETTERS_SYLLABLES = "LETTERS_SYLLABLES"
    LEXICO_VISUAL = "LEXICO_VISUAL"
    PSEUDOWORDS = "PSEUDOWORDS"
    DICTATION_STT = "DICTATION_STT"
    COPY = "COPY"
    RAPID_NAMING = "RAPID_NAMING"
    COMPREHENSION = "COMPREHENSION"
